services:
  naspt-mpv2:
    container_name: naspt-mpv2
    image: jxxghp/moviepilot-v2:latest
    environment:
      - LEAVES_UID=10971
      - LEAVES_PASSKEY=e0405a9d0de9e3b112ef78ac3d9c7975
      - TZ=Asia/Shanghai
      - SUPERUSER=admin
      - API_TOKEN=nasptnasptnasptnasptnaspt
      - AUTO_UPDATE_RESOURCE=false
      - MOVIEPILOT_AUTO_UPDATE=false
      - AUTH_SITE=icc2022,leaves
      - ICC2022_UID=24730
      - ICC2022_PASSKEY=49c421073514d4d981a0cbc4174f4b23
      - PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - LANG=C.UTF-8
      - GPG_KEY=7169605F62C751356D054A26A821E680E5FA6305
      - PYTHON_VERSION=3.12.8
      - PYTHON_SHA256=c909157bb25ec114e5869124cc2a9c4a4d4c1e957ca4ff553f1edc692101154e
      - HOME=/moviepilot
      - CONFIG_DIR=/config
      - TERM=xterm
      - DISPLAY=:987
      - PUID=0
      - PGID=0
      - UMASK=000
      - PORT=3001
      - NGINX_PORT=3000
    ports:
      - ${MOVIEPILOT_V2_PORT_3001}:3001
      - ${MOVIEPILOT_V2_PORT_3000}:3000
    volumes:
      - ${DOCKER_BASE}/naspt-qb/config/qBittorrent/BT_backup:/qbtr
      - ${DOCKER_BASE}/naspt-mpv2/core:/moviepilot/.cache/ms-playwright
      - ${DOCKER_BASE}/naspt-mpv2/config:/config
      - ${MEDIA_BASE}:/media
    restart: always
    x-meta:
      name: naspt-mpv2
      description: 容器服务
      configUrl: ''

  naspt-csf:
    container_name: naspt-csf
    image: allanpk716/chinesesubfinder:latest
    environment:
      - PGID=0
      - UMASK=022
      - PUID=0
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - TZ=Asia/Shanghai
      - PERMS=true
      - 'PS1=\u@\h:\w $ '
    ports:
      - ${CHINESESUBFINDER_PORT_19035}:19035
    volumes:
      - ${DOCKER_BASE}/naspt-csf/config:/config
      - ${DOCKER_BASE}/naspt-csf/app/cache:/app/cache
      - ${MEDIA_BASE}:/media
    restart: always
    x-meta:
      name: naspt-csf
      description: 容器服务
      configUrl: ''

  naspt-qb:
    container_name: naspt-qb
    image: linuxserver/qbittorrent:4.6.4
    environment:
      - SavePatch=/media/downloads
      - TempPatch=/media/downloads
      - WEBUI_PORT=9000
      - PUID=0
      - PGID=0
      - UMASK=022
      - TZ=Asia/Shanghai
      - PATH=/lsiopy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - 'PS1=$(whoami)@$(hostname):$(pwd)\$ '
      - HOME=/config
      - TERM=xterm
      - S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0
      - S6_VERBOSITY=1
      - S6_STAGE2_HOOK=/docker-mods
      - VIRTUAL_ENV=/lsiopy
      - LSIO_FIRST_PARTY=true
      - XDG_CONFIG_HOME=/config
      - XDG_DATA_HOME=/config
    ports:
      - ${QBITTORRENT_PORT_9000}:9000
    volumes:
      - ${DOCKER_BASE}/naspt-qb/config:/config
      - ${MEDIA_BASE}:/media
    restart: always
    x-meta:
      name: naspt-qb
      description: 容器服务
      configUrl: ''

  naspt-emby:
    container_name: naspt-emby
    image: amilys/embyserver:beta
    environment:
      - GID=0
      - UMASK=022
      - UID=0
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - LANG=en_US.UTF-8
      - HOME=/tmp
      - AMDGPU_IDS=/share/libdrm/amdgpu.ids
      - FONTCONFIG_PATH=/etc/fonts
      - LD_LIBRARY_PATH=/lib:/system
      - LIBVA_DRIVERS_PATH=/lib/dri
      - OCL_ICD_VENDORS=/etc/OpenCL/vendors
      - PCI_IDS_PATH=/share/hwdata/pci.ids
      - SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
      - GIDLIST=0
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
      - IGNORE_VAAPI_ENABLED_FLAG=false
      - XDG_CACHE_HOME=/config/cache
    ports:
      - ${EMBYSERVER_PORT_8096}:8096
    volumes:
      - ${MEDIA_BASE}:/media
      - ${DOCKER_BASE}/naspt-emby/config:/config
    restart: always
    devices:
      - /dev/dri:/dev/dri
    x-meta:
      name: naspt-emby
      description: 容器服务
      configUrl: ''

  naspt-tr:
    container_name: naspt-tr
    image: linuxserver/transmission:4.0.5
    environment:
      - PASS=a123456!@
      - TRANSMISSION_WEB_HOME=/config/2/src
      - PUID=0
      - PGID=0
      - UMASK=022
      - TZ=Asia/Shanghai
      - USER=admin
      - PATH=/lsiopy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - 'PS1=$(whoami)@$(hostname):$(pwd)\$ '
      - HOME=/root
      - TERM=xterm
      - S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0
      - S6_VERBOSITY=1
      - S6_STAGE2_HOOK=/docker-mods
      - VIRTUAL_ENV=/lsiopy
      - LSIO_FIRST_PARTY=true
    ports:
      - ${TRANSMISSION_PORT_9091}:9091
    volumes:
      - ${DOCKER_BASE}/naspt-tr/config:/config
      - ${MEDIA_BASE}:/media
    restart: always
    x-meta:
      name: naspt-tr
      description: 容器服务
      configUrl: ''

x-meta:
  name: 家庭影院
  description: Docker容器管理项目
  version: 1.0.0
  author: System
  category: container

  env:
    DOCKER_BASE:
      value: /volume1/docker
      description: Docker容器基础目录
    MEDIA_BASE:
      value: /home/media
      description: 媒体文件存储目录
    TRANSMISSION_PORT_9091:
      value: '9091'
      description: 服务端口映射
    EMBYSERVER_PORT_8096:
      value: '8096'
      description: 服务端口映射
    MOVIEPILOT_V2_PORT_3001:
      value: '3001'
      description: 服务端口映射
    QBITTORRENT_PORT_9000:
      value: '9000'
      description: 服务端口映射
    MOVIEPILOT_V2_PORT_3000:
      value: '3000'
      description: 服务端口映射
    CHINESESUBFINDER_PORT_19035:
      value: '19035'
      description: 服务端口映射
