x-meta:
  name: Docker容器项目
  description: Docker容器管理项目
  version: 1.0.0
  author: System
  category: container
  env:
    MOVIEPILOT_V2_PORT_3000:
      value: '4444'
      description: ''
    BASE_1:
      value: /mnt/host/volume1/docker/chinese-sub-finder
      description: ''
    BASE_2:
      value: /mnt/host/volume1/docker
      description: ''
    BASE_3:
      value: /Users/lizhiqiang/testDocker/new
      description: ''
    BASE_4:
      value: /mnt/host/volume1
      description: ''

services:

  moviepilot-v2-23:
    container_name: moviepilot-v2-23
    image: ccr.ccs.tencentyun.com/naspt/moviepilot-v2:latest
    environment:
      - DISPLAY=:987
      - NGINX_PORT=3000
      - PORT=3001
      - MOVIEPILOT_AUTO_UPDATE=release
      - PYTHON_VERSION=3.12.8
      - PGID=0
      - LANG=C.UTF-8
      - PUID=0
      - PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - GPG_KEY=7169605F62C751356D054A26A821E680E5FA6305
      - HOME=/moviepilot
      - CONFIG_DIR=/config
      - TERM=xterm
      - TZ=Asia/Shanghai
      - PYTHON_SHA256=c909157bb25ec114e5869124cc2a9c4a4d4c1e957ca4ff553f1edc692101154e
      - UMASK=000
    ports:
      - ${MOVIEPILOT_V2_PORT_3000}:3000
    volumes:
      - ${BASE_3}/docker/config:/config
    networks:
      - docker_default
    restart: always
    x-meta:
      name: moviepilot-v2-23
      description: 容器服务
      configUrl: ''

  transmission:
    container_name: transmission
    image: linuxserver/transmission:4.0.5
    environment:
      - TZ=Asia/Shanghai
      - USER=admin
      - PASS=a123456!@
      - TRANSMISSION_WEB_HOME=/config/2/src
      - PUID=0
      - PGID=0
      - UMASK=18
      - PATH=/lsiopy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - 'PS1=$(whoami)@$(hostname):$(pwd)\$ '
      - HOME=/root
      - TERM=xterm
      - S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0
      - S6_VERBOSITY=1
      - S6_STAGE2_HOOK=/docker-mods
      - VIRTUAL_ENV=/lsiopy
      - LSIO_FIRST_PARTY=true
    volumes:
      - ${BASE_2}/transmission/config:/config
      - ${BASE_4}/media:/media
    network_mode: host
    restart: always
    x-meta:
      name: transmission
      description: 容器服务
      configUrl: ''

  qbittorrent:
    container_name: qbittorrent
    image: linuxserver/qbittorrent:4.6.4
    environment:
      - TZ=Asia/Shanghai
      - WEBUI_PORT=8080
      - SavePatch=/media/downloads
      - TempPatch=/media/downloads
      - PUID=0
      - PGID=0
      - UMASK=18
      - PATH=/lsiopy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - 'PS1=$(whoami)@$(hostname):$(pwd)\$ '
      - HOME=/config
      - TERM=xterm
      - S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0
      - S6_VERBOSITY=1
      - S6_STAGE2_HOOK=/docker-mods
      - VIRTUAL_ENV=/lsiopy
      - LSIO_FIRST_PARTY=true
      - XDG_CONFIG_HOME=/config
      - XDG_DATA_HOME=/config
    volumes:
      - ${BASE_4}/media:/media
      - ${BASE_2}/qBittorrent/config:/config
    network_mode: host
    restart: always
    x-meta:
      name: qbittorrent
      description: 容器服务
      configUrl: ''

  chinese-sub-finder:
    container_name: chinese-sub-finder
    image: allanpk716/chinesesubfinder:latest
    environment:
      - PUID=0
      - PGID=0
      - UMASK=18
      - TZ=Asia/Shanghai
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - PERMS=true
      - 'PS1=\u@\h:\w $ '
    volumes:
      - ${BASE_1}/config:/config
      - ${BASE_4}/media:/media
      - ${BASE_1}/cache:/app/cache
    network_mode: host
    restart: always
    x-meta:
      name: chinese-sub-finder
      description: 容器服务
      configUrl: ''

  emby-offical:
    container_name: emby-offical
    image: linuxserver/emby:latest
    environment:
      - PUID=0
      - PGID=0
      - UMASK=18
      - TZ=Asia/Shanghai
      - PATH=/lsiopy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - HOME=/root
      - LANGUAGE=en_US.UTF-8
      - LANG=en_US.UTF-8
      - TERM=xterm
      - S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0
      - S6_VERBOSITY=1
      - S6_STAGE2_HOOK=/docker-mods
      - VIRTUAL_ENV=/lsiopy
      - LSIO_FIRST_PARTY=true
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
    volumes:
      - ${BASE_2}/emby:/config
      - ${BASE_4}/media:/media
    network_mode: host
    restart: always
    devices:
      - /dev/dri:/dev/dri
    x-meta:
      name: emby-offical
      description: 容器服务
      configUrl: ''

networks:

  default:
    external: true
    name: bridge
