x-meta:
  name: Docker容器项目
  description: Docker容器管理项目
  version: 1.0.0
  author: System
  category: container
  env:
    CLOUD_MEDIA_SYNC_PORT_9096: '9096'
    CLOUD_MEDIA_SYNC_PORT_9527: '9527'
    BASE_1: /Users/lizhiqiang/testDocker
services:
  cms_backup_backup:
    container_name: cms_backup_backup
    image: imaliang/cloud-media-sync:latest
    environment:
      - PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - LANG=C.UTF-8
      - GPG_KEY=7169605F62C751356D054A26A821E680E5FA6305
      - PYTHON_VERSION=3.12.7
      - PYTHON_SHA256=24887b92e2afd4a2ac602419ad4b596372f67ac9b077190f459aba390faf5550
      - TZ=Asia/Shanghai
      - TERM=xterm
      - PUID=0
      - PGID=0
      - UMASK=022
      - HOME=/cms
      - RUN_ENV=online
      - CMS_API_TOKEN=cloud_media_sync
      - EMBY_PROXY_PORT=9096
      - EMBY_HOST_PORT=http://172.17.0.1:8096
      - EMBY_API_KEY=xxx
      - IMAGE_CACHE_POLICY=3
      - PYTHONPATH=/cms/cms-api
    ports:
      - ${CLOUD_MEDIA_SYNC_PORT_9096}:9096
      - ${CLOUD_MEDIA_SYNC_PORT_9527}:9527
    volumes:
      - ${BASE_1}/ccc:/config
    networks:
      - bridge
    restart: always
    x-meta:
      name: cms_backup_backup
      description: 容器服务
      configUrl: ''
