x-meta:
  name: Docker容器项目
  description: Docker容器管理项目
  version: 1.0.0
  author: System
  category: container
  env:
    BASE_2: /var/lib/docker
services:
  naspt-allinone-format:
    container_name: naspt-allinone-format
    image: ccr.ccs.tencentyun.com/naspt/allinone_format:latest
    command:
      - php
      - -S
      - '[::]:35456'
      - -t
      - public
      - index.php
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - TZ=Asia/Shanghai
    volumes:
      - ${BASE_2}/volumes/8902311fd9b5e4236abb386bee631285173c994f6a13917c0c319111d492c961/_data:/app/config
    network_mode: host
    restart: always
    x-meta:
      name: naspt-allinone-format
      description: 容器服务
      configUrl: ''
