x-meta:
  name: Docker容器项目
  description: Docker容器管理项目
  version: 1.0.0
  author: System
  category: container
  env:
    EMBY_PORT_8096: '38096'
    BASE_1: /Users/lizhiqiang/testDocker
services:
  naspt-115-emby:
    container_name: naspt-115-emby
    image: linuxserver/emby:latest
    environment:
      - PATH=/lsiopy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - LANGUAGE=en_US.UTF-8
      - S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0
      - PUID=0
      - LSIO_FIRST_PARTY=true
      - TERM=xterm
      - S6_VERBOSITY=1
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
      - LANG=en_US.UTF-8
      - UMASK=022
      - VIRTUAL_ENV=/lsiopy
      - S6_STAGE2_HOOK=/docker-mods
      - PGID=0
      - HOME=/root
    ports:
      - ${EMBY_PORT_8096}:8096
    volumes:
      - ${BASE_1}/new/docker/115/naspt-115-emby/config:/config
      - ${BASE_1}/new/media:/media
    networks:
      - bridge
    restart: always
    x-meta:
      name: naspt-115-emby
      description: 容器服务
      configUrl: ''
