x-meta:
  name: Docker容器项目
  description: Docker容器管理项目
  version: 1.0.0
  author: System
  category: container
  env: {
    }
services:
  naspt-allinone:
    container_name: naspt-allinone
    image: ccr.ccs.tencentyun.com/naspt/allinone:latest
    command:
      - -tv=true
      - -aesKey=swj6pnb4h6xyvhpq69fgae2bbpjlb8y2
      - -userid=5892131247
      - -token=9209187973c38fb7ee461017e1147ebe43ef7d73779840ba57447aaa439bac301b02ad7189d2f1b58d3de8064ba9d52f46ec2de6a834d1373071246ac0eed55bb3ff4ccd79d137
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    network_mode: host
    restart: always
    x-meta:
      name: naspt-allinone
      description: 容器服务
      configUrl: ''
