x-meta:
  name: Docker容器项目
  description: Docker容器管理项目
  version: 1.0.0
  author: System
  category: container
  env:
    V2RAYA_PORT_2017: '2017'
    BASE_1: /Users/lizhiqiang/testDocker
services:
  v2ray:
    container_name: v2ray
    image: mzz2017/v2raya:latest
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    ports:
      - ${V2RAYA_PORT_2017}:2017
    volumes:
      - ${BASE_1}/new/docker:/etc/v2raya
    networks:
      - bridge
    restart: always
    x-meta:
      name: v2ray
      description: 容器服务
      configUrl: ''
