name: Sync to Gitee
on:
  push:
    branches: [main]
    tags: ['v*']

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Mirror to Gitee
        uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_SSH_KEY }}
        with:
          source-repo: https://github.com/kidoneself/DockPilot.git
          destination-repo: git@gitee.com:kiditer/dockpilot.git 